# permissions for end users to view ngloys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ngloy-viewer-role
rules:
- apiGroups:
  - nginx.com.kblog.club
  resources:
  - ngloys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nginx.com.kblog.club
  resources:
  - ngloys/status
  verbs:
  - get
