apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-system
data:
  prometheus.yml: |
   global:
    scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    #scrape_timeout: 600s
   #rule_files:
   # - "rules/*.yml"

     # scrape_timeout is set to the global default (10s).

   scrape_configs:
    - job_name: 'master'
      static_configs:
      - targets: ['192.168.139.128:32257']
      scrape_interval: 15s
    - job_name: 'node01'
      static_configs:
      - targets: ['192.168.139.130:32257']
      scrape_interval: 15s
    - job_name: 'node02'
      static_configs:
      - targets: ['192.168.139.129:32257']
      scrape_interval: 60s
    - job_name: 'ali-1'
      static_configs:
      - targets: ['139.224.65.35:9100']
      scrape_interval: 15s
    - job_name: 'ali-2'
      static_configs:
      - targets: ['139.196.47.104:9100']
      scrape_interval: 15s
    - job_name: 'tengxun'
      static_configs:
      - targets: ['118.25.128.189:9100']
      scrape_interval: 15s
