# permissions for end users to edit proms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prom-editor-role
rules:
- apiGroups:
  - prom.my.domain
  resources:
  - proms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prom.my.domain
  resources:
  - proms/status
  verbs:
  - get
