#!/bin/sh
#--SQL UPDATE SHELL--
echo "SQL_updata_exe Start" >> /workhome/itcc/work/logs/S2.log
_exec_ksh=/workhome/itcc/work/ini/batch_common.conf
if [ ! -f ${_exec_ksh} ]
then
    echo "環境設定ファイルが存在しません"
    exit 1
fi
. ${_exec_ksh}
LANGNAME=`env |grep "LANG=ja_JP" |cut -c 6-`
CHNGLANG=

if [ "${LANGNAME}" = "ja_JP.sjis" ]; then
  CHNGLANG="-s"
elif [ "${LANGNAME}" = "ja_JP.eucjp" ]; then
  CHNGLANG="-e"
else
  CHNGLANG="-w"
fi

ORACLE_BASE=/opt/oracle
export ORACLE_BASE
ORACLE_HOME=$ORACLE_BASE/product/11.2.0/client_1
export ORACLE_HOME
NLS_LANG=$3
export NLS_LANG

#cd

#②作業実行日(YYMMDD)]/[②X-POINTの番号_SQLファイル
sql_log_name_2=sql_update_`basename ${1} | cut -d '_' -f1`_2.log
OUTLOGDIR=${TEMP_PATH}/${sql_log_name_2}
echo "OUTLOGDIR:${OUTLOGDIR}" >> /workhome/itcc/work/logs/S2.log
if [ "$4" = "" -o "$4" = "-r" -o "$4" = "-rc" ]; then
$ORACLE_HOME/bin/sqlplus $2 << EOF > ${OUTLOGDIR}
@$1
;
rollback;
exit
EOF
fi

nkf ${CHNGLANG} ${OUTLOGDIR}

if [ "$4" = "" -o "$4" = "-commit" -o "$4" = "-rc" ]; then
  if [ "$4" != "-commit" ]; then
    while true
    do
      echo "entry commit or rollback:"
      read GETLINE
      if [ "$GETLINE" = "commit" -o "$GETLINE" = "rollback" ]; then
        break
      fi
    done
  else
    GETLINE="commit"
  fi
  
  if [ "$GETLINE" = "commit" ]; then
$ORACLE_HOME/bin/sqlplus $2 << EOF > ${OUTLOGDIR}
@$1
;
commit;
exit
EOF
nkf ${CHNGLANG} ${OUTLOGDIR}
  else
    echo 'done rollback'
  fi
fi
