#!/bin/sh
#--sql select shell--

LANGNAME=`env |grep "LANG=ja_JP" |cut -c 6-`
CHNGLANG=
echo "SQL-exe-start" >> /workhome/itcc/work/logs/param_test.log
if [ "${LANGNAME}" = "ja_JP.sjis" ]; then
  CHNGLANG="-s"
elif [ "${LANGNAME}" = "ja_JP.eucjp" ]; then
  CHNGLANG="-e"
else
  CHNGLANG="-w"
fi
ORACLE_BASE=/opt/oracle
export ORACLE_BASE
ORACLE_HOME=$ORACLE_BASE/product/11.2.0/client_1
export ORACLE_HOME
NLS_LANG=$3
export NLS_LANG
$ORACLE_HOME/bin/sqlplus -s $2 << EOF
@$1
;
exit
EOF
