apiVersion: v1
kind: PersistentVolume
metadata:
  name: www
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs
  nfs:
    path: "/nfs/data"
    server: 139.224.65.35 
